[pytest]
addopts = -m "not slow"

markers =
    benchmarks: run test on all benchmark datasets
    graphLibrary: These tests compare to the relativeNeighborhoodGraph package
    paperCompare: These tests compare to "A statistical approach to class separability"
    allModules: these tests use all modules in src
    random
    IM: Input module tests
    OM: Output module tests
    GM: Graph module
    N1: These tests compare to the N1 complexity value from the pymfe package
    slow: marks tests as slow (deselect with '-m "not slow"')
    Cut
    Uncut

filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning